image: archlinux
packages:
  - rustup
  - alsa-lib
sources:
  - https://github.com/Leinnan/slavic_castles
tasks:
  - setup: |
      rustup toolchain install stable
      cd slavic_castles/
      rustup run stable cargo fetch
  - build: |
      cd slavic_castles/
      cargo build
  - build_web: |
      cd slavic_castles/
      cargo install cargo-web
      cargo web build