[package]
name = "slavic_castles"
version = "0.1.0"
authors = ["Piotr Siuszko <siuszko@zoho.com>"]
edition = "2018"

[dependencies]
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ggez = "0.5.1"
structopt = "0.3.3"
rand = "0.7"
serde = "1.0.102"
serde_json = "1.0.41"

[target.wasm32-unknown-unknown.dependencies]
good-web-game = { git = "https://github.com/not-fl3/good-web-game", features = ["nalgebra"] }
rand = { version = "0.7", features = ["stdweb"] }
serde = "1.0.102"
serde_json = "1.0.41"