[package]
name = "slavic_castles"
version = "0.1.0"
authors = ["Piotr Siuszko <siuszko@zoho.com>"]
edition = "2018"

[dependencies]
quicksilver = "0.3.20"
serde = "1.0.103"
serde_json = "1.0.44"
nalgebra = "0.19.0"
ezing = "0.2.1"
rand = { version = "0.7", features = ["stdweb"] }